version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: my_secure_password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - "./uploads:/uploads"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://myapp_user:my_secure_password@db:5432/myapp_db
      RAILS_ENV: development
      BUNDLE_WITHOUT: ""

volumes:
  db_data:
